name: CopeLitigation
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6240969
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Cope Litigation Paralegal Services
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1D2030'
    - '#5B5442'
    - '#C8B3A3'
    - '#F3F2F1'
    - '#747299'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
